version: '3.8'

services:
  max-ng-backend:
    image: max-ng-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    env_file: .env
    ports:
      - 3000:3000
